dimforge/nphysics

README.md

readme for #25

---

README.md
src/detection/activation_manager.rs
src/detection/detector.rs
src/detection/joint/joint_manager.rs
src/integration/euler.rs
src/integration/translational_ccd_motion_clamping.rs
src/lib.rs
src/object/rigid_body.rs
src/resolution/constraint/accumulated_impulse_solver.rs
src/resolution/constraint/ball_in_socket_equation.rs
src/resolution/constraint/fixed_equation.rs
src/resolution/constraint/impulse_cache.rs
src/resolution/constraint/projected_gauss_seidel_solver.rs
src/resolution/constraint/velocity_constraint.rs
src/volumetric/volumetric_ball.rs
src/volumetric/volumetric_convex.rs
src/world/world.rs

Version of rustc: rustc 1.0.0-nightly (123a754cb 2015-03-24).

Update the library (not the examples) to the last rust-nightly.

---

.travis.yml
Makefile
src/lib.rs

As I did some tests for the 2D tensor implementation I thought that maybe it wouldn't be a bad idea to routinely run tests during a travis build.

enable tests in travis

---

.travis.payload/CSFML-2.1-CMAKE.patch
.travis.payload/install-dependencies.sh
.travis.yml

Hello Sébastien,
Travis wants people to move to their new docker-based infrastructure as it's faster.
I played around to see if we can get it to work with nphysics and yes, it works. 
Do you want to pull it?
cu
Michi

Move Travis build/testing to docker architecture.

---

examples2/compound.rs
examples2/mesh.rs
examples2/nphysics_testbed2d/src/testbed.rs
examples3/nphysics_testbed3d/src/testbed.rs
src/integration/translational_ccd_motion_clamping.rs

Version of rustc: 1.5.0-nightly (81b3b27cf 2015-10-11).

Update to the last rust-nighthly.

---

examples2/nphysics_testbed2d/Cargo.toml
examples3/nphysics_testbed3d/Cargo.toml
src/resolution/constraint/impulse_cache.rs
src/utils/deterministic_state.rs
src/utils/mod.rs

Make simulations deterministic again.

---

src/object/rigid_body_collision_groups.rs

Error on RigidBodyCollisionGroups STATIC_GROUP_ID usage

---

src/object/rigid_body.rs
src/world/world.rs

Small change - added RigidBody::mass to get the mass. Returns None if the mass is infinite (immovable object)

Added RigidBody::mass

---

src/detection/activation_manager.rs
src/integration/body_damping.rs
src/integration/body_exp_euler_integrator.rs
src/integration/body_smp_euler_integrator.rs
src/object/rigid_body.rs
src/resolution/constraint/accumulated_impulse_solver.rs

The following methods will wake-up the rigid body:
`set_lin_vel`, `set_lin_acc_scale`, `clear_linear_force`, `append_lin_force`,
`set_ang_vel`, `set_ang_acc_scale`, `clear_angular_force`, `append_ang_force`.

Wake up bodies on manual impulse or forces.

---

build/nphysics2d/Cargo.toml
build/nphysics3d/Cargo.toml
src/counters/timer.rs
src/lib.rs

Fix compilation for the wasm32-unknown-unknown target.

---

src/world/world.rs

Add method to retrieve the gravity from the world.

---

README.md

I corrected the word "sexyness" to sexiness, changed "build" to built, etc.

Grammar Revisions

---

examples3d/Cargo.toml
examples3d/boxes3.rs
examples3d/fixed_bug_tree_like_multibody3.rs
src/object/multibody.rs

Fix the size of the coriolis buffers for multibodies.

---

src/object/body_set.rs
src/object/multibody.rs
src/object/rigid_body.rs
src/world/world.rs

Clear external forces at the end of the timestep instead of the beginning

---

examples3d/Cargo.toml
nphysics_testbed2d/Cargo.toml
nphysics_testbed3d/Cargo.toml

Update testbeds to use the latest kiss3d version.

---

README.md

Hi 👋 
It seems that rust-sfml doesn't have a website, so I updated the link to reference the github page instead.
I also updated the documentation about windows since I moved the page on rust-sfml repository :)

Remove SFML mentions

---

.travis.yml

[WIP] Add wasm32 to CI build

---

src/object/rigid_body.rs

Fix inertia modification for rigid bodies in 2D.

---

src/algebra/mod.rs

Added basic traits for `ForceType` enum :3

add Clone, Copy, and Debug traits for ForceType

---

build/nphysics2d/Cargo.toml
build/nphysics3d/Cargo.toml
src/object/fem_surface.rs
src/object/fem_volume.rs

Fix #182 
This requires https://github.com/rustsim/nalgebra/pull/549 to be merged/released first.

Fix inverted element handling causing a crash

---

build/nphysics2d/Cargo.toml
build/nphysics3d/Cargo.toml
src/world/world.rs

 Activate bodies when a collider or a body touching them is removed

---

src/world/collider_world.rs

When combined with https://github.com/rustsim/ncollide/pull/271, allows the use of custom shapes.

Expose narrow-phase setter

---

examples3d/trimesh3.rs

This is just a bit of fun, but does makes the example more interesting.

Improve height map in trimesh3 example

---

src/force_generator/force_generator.rs

Document return value of `ForceGenerator::apply`

---

examples3d/constraints3.rs
src/detection/activation_manager.rs
src/joint/ball_constraint.rs
src/joint/cartesian_constraint.rs
src/joint/cylindrical_constraint.rs
src/joint/fixed_constraint.rs
src/joint/joint_constraint.rs
src/joint/mouse_constraint.rs
src/joint/pin_slot_constraint.rs
src/joint/planar_constraint.rs
src/joint/prismatic_constraint.rs
src/joint/rectangular_constraint.rs
src/joint/revolute_constraint.rs
src/joint/universal_constraint.rs
src/solver/moreau_jean_solver.rs
src/world/mechanical_world.rs

This add the possibility to specify a maximum force a joint modeled with constraints can sustain before breaking.

Make joint constraints breakable.

---

.circleci/config.yml
Cargo.toml
build/nphysics2d/Cargo.toml
build/nphysics3d/Cargo.toml
build/nphysics_testbed2d/Cargo.toml
build/nphysics_testbed3d/Cargo.toml
examples2d/Cargo.toml
examples3d/Cargo.toml
examples3d/ccd3.rs
src/joint/ball_constraint.rs
src/object/body.rs
src/object/fem_helper.rs
src/object/fem_surface.rs
src/object/fem_volume.rs
src/object/ground.rs
src/object/mass_constraint_system.rs
src/object/mass_spring_system.rs
src/object/multibody.rs
src/object/rigid_body.rs
src/world/geometrical_world.rs
src_testbed/engine.rs
src_testbed/objects/fluid.rs
src_testbed/objects/mod.rs
src_testbed/testbed.rs
src_testbed/ui.rs

This brings various small changes to prepare for the next version of salva. Most of the changes are on the testbed. However, one method has been added to the `Body` trait: `velocity_at_point` which computes the velocity at the given point on the body.

Various improvements for the next version of salva

---

src/object/rigid_body.rs

Fix max linear velocity constraint for rigid bodies

---

.circleci/config.yml
Cargo.toml
build/nphysics2d/Cargo.toml
build/nphysics3d/Cargo.toml
build/nphysics_testbed2d/Cargo.toml
build/nphysics_testbed3d/Cargo.toml
examples2d/Cargo.toml
examples3d/Cargo.toml
src/joint/mouse_constraint.rs
src/lib.rs
src/object/mass_constraint_system.rs
src/object/multibody.rs
src/solver/helper.rs
src/solver/nonlinear_sor_prox.rs
src/solver/signorini_coulomb_pyramid_model.rs
src/solver/sor_prox.rs
src_testbed/engine.rs
src_testbed/objects/ball.rs
src_testbed/objects/box_node.rs
src_testbed/objects/capsule.rs
src_testbed/objects/convex.rs
src_testbed/objects/fluid.rs
src_testbed/objects/heightfield.rs
src_testbed/objects/mesh.rs
src_testbed/objects/node.rs
src_testbed/objects/polyline.rs
src_testbed/testbed.rs
src_testbed/ui.rs

This makes nphysics compatible with the latest version of nalgebra and ncollide.
Fix #256

Update to the nalgebra 0.21

---

examples2d/all_examples2.rs
examples2d/broad_phase_filter2.rs
examples3d/all_examples3.rs
examples3d/broad_phase_filter3.rs
src/world/geometrical_world.rs

GeometricalWorld: allow the definition of a custom broad-phase pair filter
