dimforge/nphysics

- .travis.yml
This fixes a build failure in Travis CI. The build gets past the cmake failure in my fork but then hits a problem in glfw: https://travis-ci.org/bstpierre/nphysics/builds/67459074
> Use ppa for cmake 2.8.11

- examples2/Cargo.toml
- examples2/convex_vee.rs
- examples2/nphysics_testbed2d/src/engine.rs
- src/lib.rs
- src/volumetric/volumetric_convex.rs
Hello Sébastien,
I tried to play around with 2D convex shapes and noticed that they are not completely supported yet. Then I tried to patch in what's missing and to my surprise succeeded in getting a basic 2D convex demo up and running. Maybe you want to take a look at it, comment and - if everything is ok - merge?
This pull request contains the parts of nphysics.
Note: I also created "demo2Dconvex" branches in my github repositories. They have the dependencies properly set so that they compile and can be tested.
Michi
> extensions for 2D convex shape

- examples2/cross.rs
- examples2/gravity.rs
- src/detection/activation_manager.rs
- src/detection/joint/joint_manager.rs
- src/integration/translational_ccd_motion_clamping.rs
- src/world/world.rs
This makes objects removal operational and renames the method `.will_activate(...)` of the
`ActivationManager` to `.deferred_activate(...)`.
> Update to the last ncollide api + minor method renaming.

- examples2d/Cargo.toml
- examples3d/Cargo.toml
Currently the examples don't build, because `nphysics` pins the `nalgebra` and `ncollide` versions to `0.9.*` and `0.10.*` respectively, whereas the examples use wildcard dependency versions. This fixes that issue, and allows the examples to build again.
> Pin version numbers in examples

- build/nphysics3d/tests/free_sensor_update.rs
- src/object/mod.rs
- src/object/sensor.rs
- src/world/mod.rs
- src/world/world.rs
Fix #87.
The collection has to be explicitly enabled for each sensor calling `.enable_interfering_bodies_collection` and `.enable_interfering_sensors_collection`.
> Fix collection of objects in proximity of a sensor.

- src/object/sensor.rs
Haven't tested this yet, but it looks like an accidental omission.
> Add Sensor::set_collision_groups

- src/world/world.rs
Sorry if there's a reason why this method doesn't exist. Also:
- Why are Body[Mut] and BodyPart[Mut] enums instead of traits?
- Why doesn't BodyPartMut have a method to apply displacement?
> Add World::body_part_mut.

- build/nphysics2d/Cargo.toml
- build/nphysics3d/Cargo.toml
- src/counters/timer.rs
- src/lib.rs
At the moment, projects depending on wasm-bindgen [cannot use nphysics due to a transcient dependency on stdweb](https://github.com/koute/stdweb/issues/263).
This PR adds a new feature, `use-wasm-bindgen`, which uses `wasm-bindgen` instead. This is a non-breaking change, as all dependencies on `stdweb` have been moved to the special `standard` feature.
> Make nphysics compatible with projects depending on wasm-bindgen

- publish.sh
```
In publish.sh line 3:
tmp=`mktemp -d`
^-- SC2006: Use $(..) instead of legacy `..`.
In publish.sh line 5:
echo $tmp
^-- SC2086: Double quote to prevent globbing and word splitting.
In publish.sh line 7:
cp -r src $tmp/.
^-- SC2086: Double quote to prevent globbing and word
splitting.
In publish.sh line 8:
cp -r LICENSE README.md $tmp/.
^-- SC2086: Double quote to prevent globbing and
word splitting.
In publish.sh line 11:
sed 's#\.\./\.\./src#src#g' build/nphysics2d/Cargo.toml >
$tmp/Cargo.toml
^-- SC2086:
Double quote to prevent globbing and word splitting.
In publish.sh line 12:
currdir=`pwd`
^-- SC2006: Use $(..) instead of legacy `..`.
In publish.sh line 13:
cd $tmp && cargo publish
^-- SC2086: Double quote to prevent globbing and word splitting.
In publish.sh line 14:
cd $currdir …
```
> Follow `shellcheck` advices.

- README.md
- The current link for the crate badge leads to an old yanked crate: https://crates.io/crates/nphysics
- I added an extra badge for the 2D crate
- [merit](https://github.com/seanmonstar/merit/blob/master/src/main.rs) doesn't seem to support overriding the label to disambiguate the two crates
- It seems like a direct link to [shields.io](https://shields.io) is working fine for the badges
- I didn't add badges for the testbed crates because I figured it'd be too crowded and those crates aren't used as often
- Same thing applies for [ncollide](https://raw.githubusercontent.com/rustsim/ncollide/master/README.md) (I didn't create a PR yet)
> Disambiguate 2D and 3D crate badges

- .gitignore
Add `.idea/` and `.vscode/` to the `.gitignore`. My original issue only mentioned `.idea`, but I later decided to also include `.vscode` to cover both IDEs and due to it's use in all other rustsim repositories.
> Fixes rustsim/nphysics#227

- src/object/body_set.rs
- src/object/collider_set.rs
- src/world/mechanical_world.rs
The methods `BodySet::get_pair_mut` and `ColliderSet::get_pair_mut` used unsafe code to get two multiple mutable references from a pair of unique handles. In many cases this forces anyone implementing their own `BodySet` or `ColliderSet` to also use unsafe code that could have been avoided. However these functions are not necessary and the same effect can be achieved at the cost of 2 extra calls to `ColliderSet::get_pair`.
This change should have an insignificant effect on performance that might be optimized out.
In order to reflect the original functionality, I modified the if statement slightly. I did not look back far enough in the file to check, but seems likely that the if statement is no longer necessary.
```rust
// Before
if let (Some(b1), Some(b2)) = bodies.get_pair_mut(handle1, …
```
> Remove unsafe code from body and collider sets

- src/detection/activation_manager.rs
- src/force_generator/constant_acceleration.rs
- src/force_generator/force_generator.rs
- src/force_generator/spring.rs
- src/joint/ball_constraint.rs
- src/joint/cartesian_constraint.rs
- src/joint/cartesian_joint.rs
- src/joint/cylindrical_constraint.rs
- src/joint/fixed_constraint.rs
- src/joint/joint_constraint.rs
- src/joint/mouse_constraint.rs
- src/joint/pin_slot_constraint.rs
- src/joint/planar_constraint.rs
- src/joint/prismatic_constraint.rs
- src/joint/rectangular_constraint.rs
- src/joint/revolute_constraint.rs
- src/joint/universal_constraint.rs
- src/object/body_set.rs
- src/object/mass_constraint_system.rs
- src/object/mass_spring_system.rs
- src/solver/contact_model.rs
- src/solver/moreau_jean_solver.rs
- src/solver/nonlinear_constraint.rs
- src/solver/nonlinear_sor_prox.rs
- src/solver/signorini_coulomb_pyramid_model.rs
- src/solver/signorini_model.rs
- src/solver/sor_prox.rs
- src/world/geometrical_world.rs
- src/world/mechanical_world.rs
This commit prevents BodySet from polluting as a type parameter into all the core types required for physics stepping. Thanks to this, problems involved in dealing with these types in Specs usage are alleviated. However, this commit also removes the associated type of Body and always assumes dynamic dispatch on the Body type. This is an evolution of #226 that loosens future restrictions mentioned in that thread.
> Utilize BodySet as a trait object instead of param

- examples3d/Cargo.toml
- examples3d/trimesh3.rs
- src_testbed/testbed.rs
Currently cloning `master` and running `cargo test` yields two warnings, this PR cleans those up.
> Fix warnings from `cargo test`

- build/nphysics2d/Cargo.toml
- build/nphysics3d/Cargo.toml
The issue was fixed and described here: https://github.com/rustsim/nphysics/issues/241 by @cauthmann .
> Fixed dependency on Instant to work with wasm-bindgen

- src_testbed/engine.rs
- src_testbed/testbed.rs
This exposes the `set_up_axis` method in Arc Ball camera of Kiss3d that
was added by sebcrozet/kiss3d#146 for the purpose of changing the
upward-pointing axis. Note that proper camera movement had not been
implemented in the referenced pull request.
> Add set_up_axis method to testbed3d

- src/object/collider.rs
Added Collider::material_mut, spell-checked the whole file and converted imperatives to descriptions.
> Add Collider::make_mut

- .circleci/config.yml
- Cargo.toml
Building without a [patch.crates-io] for nphysics itself breaks when
using salva, because salva then pulls in another version of nphysics
through crates.io. This [patch] section in Cargo.toml makes sure that
salva will use the same working copy of nphysics.
> Fix building with indirect dependency on self.

- build/nphysics_testbed2d/Cargo.toml
- build/nphysics_testbed3d/Cargo.toml
- src_testbed/engine.rs
- src_testbed/objects/ball.rs
- src_testbed/objects/box_node.rs
- src_testbed/objects/capsule.rs
- src_testbed/objects/convex.rs
- src_testbed/objects/fluid.rs
- src_testbed/objects/heightfield.rs
- src_testbed/objects/mesh.rs
- src_testbed/objects/node.rs
- src_testbed/objects/plane.rs
- src_testbed/objects/polyline.rs
- src_testbed/testbed.rs
- src_testbed/ui.rs
This leaves all the graphics objects in `f32`, but allows using an `f64` world: Shapes are converted to an `f32` representation, and inputs are converted back.
> Make the testbed generic over RealField.

- src/lib.rs
Not sure how you feel regarding #257 but it's more or less standard to re-export dependencies from within the library. Avoids versioning issues and conflicts with other crates. Also makes the Cargo.toml a lot cleaner.
Just drop the PR if you don't agree.
> Re-export nalgebra and ncollide. Fixes #257

- src/object/body.rs
- src/object/fem_surface.rs
- src/object/fem_volume.rs
- src/object/ground.rs
- src/object/mass_constraint_system.rs
- src/object/mass_spring_system.rs
- src/object/multibody.rs
- src/object/rigid_body.rs
- src_testbed/engine.rs
- src_testbed/objects/fluid.rs
This adds a `body.num_parts` method to retrieve the number of parts of a body.
Now, `RigidBody` and `Ground` will return `None` for all parts index other than 0.
This is a breaking change because this adds a method to the `Body` trait.
> Add a method to retrieve the number of parts of a body.

- src/object/multibody_link.rs
As per the (incredibly short) conversation on Discord. This makes it *much* easier to do a broad phase collision filter preventing collisions with ancestor links while allowing collisions with sibling links.
> Expose ability to get `MultibodyLink` parent ID

- src/object/multibody.rs
Adds the ability to create a multibody builder from a boxed joint trait object.
> Add method to build multibody from boxed joint

- src/joint/joint_motor.rs
- src/joint/prismatic_joint.rs
- src/joint/revolute_joint.rs
- src/joint/unit_joint.rs
Adds a maximum target velocity to the joint motors.
As per the conversation on Discord: being able to specify a maximum velocity on the joint motors helps with loading URDF files (#268) without the defining new types.
> Add maximum target velocity to joint motors

- src/joint/prismatic_joint.rs
- src/joint/revolute_joint.rs
Correct typo present in the methods for setting max angular motor velocity.
> Correct typo in joint max angular velocity

- src/object/multibody.rs
Adds methods to view the current children of  a multibody description as well as adding a child link from a full multibody description.
> Add methods for managing children of multibody descriptions

- Cargo.toml
- build/nphysics2d/Cargo.toml
- build/nphysics3d/Cargo.toml
- build/nphysics_testbed2d/Cargo.toml
- build/nphysics_testbed3d/Cargo.toml
- examples2d/Cargo.toml
- examples2d/broad_phase_filter2.rs
- examples3d/Cargo.toml
- examples3d/broad_phase_filter3.rs
- src/joint/prismatic_joint.rs
- src/world/geometrical_world.rs
- src/world/mechanical_world.rs
- src/world/mod.rs
- src_testbed/testbed.rs
Meant to be paired with [ncollide#359](https://github.com/dimforge/ncollide/pull/359).
This utilizes the new formulation of the `BroadPhasePairFilter` trait to supply both the `BodySet` and `ColliderSet` to the broad phase pair filter. This allows for the filter to take into account information that exists in the body, such as multibody link ancestry, velocity, etc.
From the user's perspective, this removes `GeometricalWorld::set_broad_phase_pair_filter` and provides a `MechanicalWorld::step_with_filter(.., impl BroadPhasePairFilter)` where the filter has access to the body set.
> Give access to body set in broad phase filter
